const addressObjectsTableHeaders = [
    {
        title: '',
        key: 'actions',
        align: 'end',
        minWidth: 140,
        width: 140,
        maxWidth: 140,
        fixed: true,
        sortable: false,
        _$visible: true,
    },
    {
        title: '№ п/п',
        align: 'start',
        key: 'number',
        value: 'number',
        sortable: true,
        nowrap: false,
        minWidth: 80,
        _$visible: true,
    },
    {
        title: 'Наименование',
        align: 'start',
        key: 'name',
        value: 'name',
        sortable: true,
        nowrap: false,
        minWidth: 100,
        maxWidth: 200,
        _$visible: true,
    },
    {
        title: 'Инв. №',
        align: 'start',
        key: 'inventoryNumber',
        value: 'inventoryNumber',
        sortable: true,
        nowrap: false,
        _$visible: true,
    },
    {
        title: 'Наличие объекта',
        align: 'end',
        key: 'isExist',
        value: 'isExist',
        maxWidth: 80,
        sortable: true,
        nowrap: false,
        _$visible: true,
    },
    {
        title: 'Наличие дефекта',
        align: 'end',
        key: 'isDefect',
        value: 'isDefect',
        maxWidth: 80,
        sortable: true,
        nowrap: false,
        _$visible: true,
    },
    {
        title: 'Тип объекта',
        align: 'end',
        key: 'objectType',
        value: 'objectType',
        minWidth: 100,
        maxWidth: 180,
        sortable: true,
        nowrap: false,
        _$visible: true,
    },
    {
        title: 'Описание дефекта',
        align: 'end',
        key: 'defectDescription',
        value: 'defectDescription',
        sortable: true,
        nowrap: false,
        _$visible: true,
    },
]

export default addressObjectsTableHeaders;