const customerTableHeaders = [
    {
        title: '',
        key: 'actions',
        align: 'end',
        minWidth: 100,
        width: 100,
        maxWidth: 100,
        fixed: true,
        sortable: false,
        _$visible: true,
    },
    {
        title: 'Наименование',
        key: 'shortName',
        value: 'shortName',
        align: 'start',
        sortable: true,
        nowrap: false,
        _$visible: true,
    },
    {
        title: 'Email организации',
        key: 'email',
        value: 'email',
        align: 'start',
        sortable: true,
        nowrap: false,
        _$visible: true,
    },
    {
        title: 'Телефон организации',
        key: 'phoneNumber',
        value: 'phoneNumber',
        align: 'start',
        sortable: true,
        nowrap: false,
        _$visible: true,
    },
    {
        title: 'ФИО представителя',
        key: 'memberFullName',
        value: 'memberFullName',
        align: 'start',
        sortable: true,
        nowrap: false,
        _$visible: true,
    },
    {
        title: 'Должность представителя',
        key: 'memberPosition',
        value: 'memberPosition',
        align: 'start',
        sortable: true,
        nowrap: false,
        _$visible: true,
    },
    {
        title: 'Юридический адрес',
        key: 'legalAddress',
        value: 'legalAddress',
        align: 'start',
        sortable: true,
        nowrap: false,
        _$visible: true,
    },
    {
        title: 'Фактический адрес',
        key: 'physicalAddress',
        value: 'physicalAddress',
        align: 'start',
        sortable: true,
        nowrap: false,
        _$visible: true,
    },
];

export default customerTableHeaders;