export const customerTableHeaders = [
    {
        title: '',
        key: 'actions',
        align: 'end',
        minWidth: 100,
        width: 100,
        maxWidth: 100,
        fixed: true,
        sortable: false,
        _$visible: true,
    },
    {
        title: 'Наименование',
        key: 'shortName',
        value: 'shortName',
        align: 'start',
        sortable: true,
        nowrap: false,
        _$visible: true,
    },
    {
        title: 'Представитель / Должность',
        key: 'member',
        value: 'member',
        align: 'start',
        sortable: true,
        nowrap: false,
        _$visible: true,
    },
    // {
    //     title: 'Представитель / Должность',
    //     key: 'memberFullName',
    //     value: 'memberFullName',
    //     align: 'start',
    //     sortable: true,
    //     nowrap: false,
    //     _$visible: true,
    // },
    // {
    //     title: 'Должность представителя',
    //     key: 'memberPosition',
    //     value: 'memberPosition',
    //     align: 'start',
    //     sortable: true,
    //     nowrap: false,
    //     _$visible: true,
    // },
    {
        title: 'Контакты',
        key: 'contacts',
        value: 'contacts',
        align: 'start',
        sortable: true,
        nowrap: false,
        _$visible: true,
    },
    // {
    //     title: 'Контакты',
    //     key: 'email',
    //     value: 'email',
    //     align: 'start',
    //     sortable: true,
    //     nowrap: false,
    //     _$visible: true,
    // },
    // {
    //     title: 'Телефон организации',
    //     key: 'phoneNumber',
    //     value: 'phoneNumber',
    //     align: 'start',
    //     sortable: true,
    //     nowrap: false,
    //     _$visible: true,
    // },
    {
        title: 'Юридический адрес',
        key: 'legalAddress',
        value: 'legalAddress',
        align: 'start',
        sortable: true,
        nowrap: false,
        _$visible: true,
    },
    {
        title: 'Фактический адрес',
        key: 'physicalAddress',
        value: 'physicalAddress',
        align: 'start',
        sortable: true,
        nowrap: false,
        _$visible: true,
    },
];